Allow psr/container 2.0.*
laminas/laminas-servicemanager pull request #175
Opened 2023-02-15 13:53 UTC by tobilektri

Should allow psr/container 2.0.2 - not only 1.1.2

Changes:
https://github.com/php-fig/container/compare/2.0.2...1.1.2

|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### Description

2023-02-15 14:09 UTC, Ocramius requested changes
Sadly not as simple as it sounds, as this represents a major BC break for downstream.

2023-02-15 14:09 UTC, Ocramius commented
Duplicate of #151

2023-02-15 14:09 UTC, closed without merging

2023-02-15 16:04 UTC, tobilektri commented
@Ocramius could you please explain why adding a new allowed version is a "major BC break for downstream" - the change in the psr/container is not a major BC in my opinion. 
What has to be fixed to allow the ^2.0?

2023-02-15 16:09 UTC, Ocramius commented
This snippet makes it more clear: https://3v4l.org/DfZYG

```php
<?php

class ServiceManager {
    function has($name): bool { return true; } 
}

final class UserlandContainer extends ServiceManager
{
    function has($name) { return true; } 
}
```

```
Fatal error: Declaration of UserlandContainer::has($name) must be compatible with ServiceManager::has($name): bool in /in/DfZYG on line 9

Process exited with code 255.
```

2023-02-16 07:39 UTC, tobilektri commented
So this change will only take place with the (next?) Major Version release of laminas-servicemanager?

2023-02-16 14:44 UTC, froschdesign commented
> So this change will only take place with the (next?) Major Version release of laminas-servicemanager?

Correct. See also the related [milestone for the next major version](https://github.com/laminas/laminas-servicemanager/milestone/2).