QA: Use a more specific array shape in services configuration of ServiceManager
laminas/laminas-servicemanager pull request #213
Opened 2023-10-14 21:24 UTC by rieschl

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

This PR adds a more specific array shape for the `services` key in `ServiceManagerConfiguration`.

fixes #212

2023-10-16 16:32 UTC, boesing requested changes

2023-10-16 16:32 UTC, boesing commented on src/ServiceManager.php
> + *     services?: array<string,object|array<array-key,mixed>>,
As requested in #212, please use `array<mixed>` instead.

2023-10-16 16:33 UTC, boesing commented on src/ServiceManager.php
> + *     services?: array<string,object|array<array-key,mixed>>,
@laminas/technical-steering-committee should we enforce this kind of `array` notation via our codestandard and if so, are there existing rules for that?

2023-10-24 11:18 UTC, boesing approved these changes
LGTM, ~will see when I find some time to prepare a release~

nvm, is just a patch. going to release now.

2023-10-24 11:19 UTC, merged

2023-10-24 11:54 UTC, rieschl commented
> LGTM, ~will see when I find some time to prepare a release~
> 
> nvm, is just a patch. going to release now.

thanks!