Allow varexporter v0.5
laminas/laminas-servicemanager pull request #237
Opened 2024-05-13 20:57 UTC by snapshotpl

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

Support for brick/varexporter v0.5.0 to turn supports nikic/PHP-Parser v5 and enabling upgrades to PHPUnit 11 in downstream projects.

2024-05-13 20:58 UTC, Ocramius requested changes
With latest dependencies, this still installed 0.4.x

`  - Downloading brick/varexporter (0.4.0)`

2024-05-13 21:00 UTC, snapshotpl commented
Yeah, probably same like here :-( https://github.com/laminas/laminas-config-aggregator/pull/45

2024-06-11 10:22 UTC, kersysgediminas commented
@Ocramius 
> With latest dependencies, this still installed 0.4.x
> 
> ` - Downloading brick/varexporter (0.4.0)`

This is because `brick/varexporter (0.5.0)` requires `nikic/php-parser (5.0.0)`, but  `vimeo/psalm` only supports `nikic/php-parser (4.0.0)`. However  `vimeo/psalm` is only used in `require-dev` and `brick/varexporter (0.5.0)` wouldn't be blocked when installing `laminas/laminas-servicemanager` as a required dependency

2024-06-11 11:56 UTC, Xerkus commented
Wait, why service manager needs var exporter?

2024-06-11 12:04 UTC, snapshotpl commented
https://github.com/laminas/laminas-servicemanager/blob/ae01570ecdf4559aef2f15d4e79e8c36874f7416/src/Tool/FactoryCreator.php#L171

2024-07-04 09:36 UTC, mrVrAlex commented
So signature VarExporter::export backward compatibility between v0.4 & v0.5 I believe we can safe merge this PR without any consequences...

2024-07-04 09:40 UTC, Ocramius approved these changes
:ship:  then :-)

2024-07-04 09:40 UTC, merged

2024-07-04 09:40 UTC, Ocramius commented
Thanks @snapshotpl @mrVrAlex @kersysgediminas