Initial support for PHP 8.0
laminas/laminas-servicemanager pull request #51
Opened 2020-07-01 19:12 UTC by snapshotpl

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

This patch removes deprecation errors from comes from reflection API in PHP 8.0

2020-07-01 21:46 UTC, boesing requested changes

2020-07-01 21:46 UTC, boesing commented on .travis.yml
> +        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
There is a new argument `--ignore-platform-req` which can be used to ignore specific requirements.

We probably should use `--ignore-platform-req=php` for nightly builds tho.

https://twitter.com/naderman/status/1277941647003848707

2020-07-01 21:51 UTC, boesing approved these changes

2020-07-01 21:51 UTC, boesing commented on .travis.yml
> +        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
Never mind. Thats a dedicated Composer 2 feature 👎

2020-07-02 05:31 UTC, snapshotpl commented
IMO we need to merge this also into 3.x also with nightly builds

2020-11-17 23:27 UTC, merged

2020-11-17 23:27 UTC, boesing commented
Thanks, @snapshotpl!