Docs/delegators and aliases
laminas/laminas-servicemanager pull request #91
Opened 2021-07-16 14:39 UTC by gsteel

|    Q          |   A
|-------------- | ------
| Documentation | yes

### Description

More information in #90 - This pull adds information to delegators.md to illustrate delegator behaviour wrt service aliases.

I also added a fairly verbose test case to illustrate.

Hang fire whilst I force push for DCO 😅

2021-07-19 09:01 UTC, gsteel commented
Added 2 commits that fix a couple of linting errors elsewhere in the docs. The PHPCS failure is not fixable without upgrading Laminas Coding Standard as per #87

2021-07-19 20:04 UTC, froschdesign requested changes

2021-07-19 20:04 UTC, froschdesign commented on docs/book/delegators.md
> +        Buzzer::class => InvokableFactory::class,
```suggestion
        Buzzer::class => Laminas\ServiceManager\Factory\InvokableFactory::class,
```

2021-07-19 20:04 UTC, froschdesign commented on docs/book/delegators.md
> +        Buzzer::class => InvokableFactory::class,
```suggestion
        Buzzer::class => Laminas\ServiceManager\Factory\InvokableFactory::class,
```

2021-07-19 20:04 UTC, froschdesign commented on docs/book/delegators.md
> +            BuzzerDelegatorFactory::class,
```suggestion
            BuzzerDelegatorFactory::class, // will not be executed
```

2021-07-19 20:04 UTC, froschdesign commented on docs/book/delegators.md
> +For example, given the following configuration, **no delegation would occur**:
If something is described as not working, then it must also be described how it works correctly.

2021-07-24 12:05 UTC, boesing commented
I've retargeted 3.7.x and rebased against that. codestyle checks should pass as of now.
DCO is broken because of an unsigned commit within the rebased commits. So actually, thats not your fault.

2021-07-24 19:32 UTC, Ocramius commented
Applied minor CS fixes, rebased and merging now :-)

GPG signatures most likely unverifiable due to rebase by third-party (me), but also not required here.

2021-07-24 19:33 UTC, Ocramius approved these changes
Thanks @gsteel!

2021-07-24 19:33 UTC, merged