Improve ServiceManager::has() performance
laminas/laminas-servicemanager pull request #93
Opened 2021-07-23 14:32 UTC by koenkivits

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

We noticed that `ServiceManager::has()` was a pretty big bottleneck on a page using a very large amount of view helpers to render a large amount of data:

![image](https://user-images.githubusercontent.com/1873829/126794579-cdf965a8-0ce7-40a2-b08a-04d51514a744.png)

This was on a total duration of 5.61 seconds, which means it spent 87.5% of the time checking if services exist.

The problem seemed to be caused by [the way `has()` uses dynamically created closures](https://github.com/laminas/laminas-servicemanager/blob/e76870240e368edf699c50d4bbf32607ac94145c/src/ServiceManager.php#L967-L1011). This PR refactors that code to implement the same behavior using 2 private methods, avoiding the overhead that comes with it.

We're using this patch in production now and for this specific example the performance has improved drastically:

![image](https://user-images.githubusercontent.com/1873829/126795870-e3865940-12a7-417a-b3f3-10075ce09ece.png)

The logic itself remained exactly the same, I only changed the way it was written. I hope it helps, please let me know if I need to fix or clarify anything! :)

2021-07-23 19:05 UTC, Ocramius requested changes
Stellar work!

Could you run a before/after on https://github.com/laminas/laminas-servicemanager/tree/e76870240e368edf699c50d4bbf32607ac94145c/benchmarks too though?

I think we have no tests using `has()` in there either, and we really should add them for this patch :-\

2021-07-24 12:25 UTC, boesing commented
@Ocramius I've added phpbench in #94 so we can rebase this branch against 3.7.x afterwards.

2021-07-24 12:42 UTC, boesing commented
## Benchmark on my MBP 2019 2,8 GHz i7

### Before

```
PHPBench @git_tag@ running benchmarks...
with configuration file: /Users/max/git/laminas/laminas-servicemanager/phpbench.json
with PHP version 7.4.21, xdebug ✔, opcache ❌

\LaminasBench\ServiceManager\HasNewServicesBench

    benchHasFactory1........................R1 I1 [μ Mo]/r: 3.032 3.073 (μs) [μSD μRSD]/r: 0.068μs 2.23%
    benchHasInvokable1......................R1 I9 [μ Mo]/r: 3.813 3.796 (μs) [μSD μRSD]/r: 0.081μs 2.14%
    benchHasService1........................R2 I9 [μ Mo]/r: 3.093 3.054 (μs) [μSD μRSD]/r: 0.073μs 2.36%
    benchFetchFactoryAlias1.................R1 I6 [μ Mo]/r: 3.736 3.788 (μs) [μSD μRSD]/r: 0.083μs 2.22%
    benchHasRecursiveFactoryAlias1..........R3 I6 [μ Mo]/r: 3.839 3.861 (μs) [μSD μRSD]/r: 0.065μs 1.70%
    benchFetchRecursiveFactoryAlias2........R2 I8 [μ Mo]/r: 3.963 3.986 (μs) [μSD μRSD]/r: 0.102μs 2.58%
    benchFetchAbstractFactoryFoo............R1 I0 [μ Mo]/r: 4.821 4.778 (μs) [μSD μRSD]/r: 0.087μs 1.81%

(best [mean mode] worst) = 2.923 [3.757 3.762] 3.128 (μs)
⅀T: 262.978μs μSD/r 0.080μs μRSD/r: 2.148%
Subjects: 7, Assertions: 0, Warnings: 0, Errors: 0, Failures: 0
```

```
→ php74 vendor/bin/phpbench  run benchmarks/HasCachedServicesBench.php 
PHPBench @git_tag@ running benchmarks...
with configuration file: /Users/max/git/laminas/laminas-servicemanager/phpbench.json
with PHP version 7.4.21, xdebug ✔, opcache ❌

\LaminasBench\ServiceManager\HasCachedServicesBench

    benchHasFactory1........................R1 I19 [μ Mo]/r: 2.901 2.823 (μs) [μSD μRSD]/r: 0.093μs 3.20%
    benchHasInvokable1......................R1 I12 [μ Mo]/r: 3.612 3.574 (μs) [μSD μRSD]/r: 0.090μs 2.48%
    benchHasService1........................R2 I17 [μ Mo]/r: 2.999 3.022 (μs) [μSD μRSD]/r: 0.078μs 2.60%
    benchHasAlias1..........................R1 I10 [μ Mo]/r: 3.130 3.160 (μs) [μSD μRSD]/r: 0.069μs 2.22%
    benchHasRecursiveAlias1.................R2 I17 [μ Mo]/r: 3.119 3.092 (μs) [μSD μRSD]/r: 0.074μs 2.38%
    benchHasRecursiveAlias2.................R1 I3 [μ Mo]/r: 3.290 3.251 (μs) [μSD μRSD]/r: 0.090μs 2.72%
    benchHasAbstractFactoryService..........R2 I18 [μ Mo]/r: 5.064 5.046 (μs) [μSD μRSD]/r: 0.097μs 1.92%

(best [mean mode] worst) = 2.785 [3.445 3.424] 3.040 (μs)
⅀T: 482.300μs μSD/r 0.084μs μRSD/r: 2.504%
Subjects: 7, Assertions: 0, Warnings: 0, Errors: 0, Failures: 0
```

## After
```
→ php74 vendor/bin/phpbench  run benchmarks/HasCachedServicesBench.php 
PHPBench @git_tag@ running benchmarks...
with configuration file: /Users/max/git/laminas/laminas-servicemanager/phpbench.json
with PHP version 7.4.21, xdebug ✔, opcache ❌

\LaminasBench\ServiceManager\HasCachedServicesBench

    benchHasFactory1........................R1 I4 [μ Mo]/r: 0.571 0.580 (μs) [μSD μRSD]/r: 0.014μs 2.49%
    benchHasInvokable1......................R1 I8 [μ Mo]/r: 0.889 0.881 (μs) [μSD μRSD]/r: 0.021μs 2.34%
    benchHasService1........................R1 I1 [μ Mo]/r: 0.571 0.570 (μs) [μSD μRSD]/r: 0.014μs 2.50%
    benchHasAlias1..........................R1 I7 [μ Mo]/r: 0.595 0.594 (μs) [μSD μRSD]/r: 0.012μs 2.02%
    benchHasRecursiveAlias1.................R1 I1 [μ Mo]/r: 0.606 0.602 (μs) [μSD μRSD]/r: 0.012μs 2.01%
    benchHasRecursiveAlias2.................R2 I17 [μ Mo]/r: 0.608 0.612 (μs) [μSD μRSD]/r: 0.011μs 1.87%
    benchHasAbstractFactoryService..........R1 I4 [μ Mo]/r: 1.171 1.181 (μs) [μSD μRSD]/r: 0.025μs 2.10%

(best [mean mode] worst) = 0.545 [0.716 0.717] 0.590 (μs)
⅀T: 100.238μs μSD/r 0.016μs μRSD/r: 2.193%
Subjects: 7, Assertions: 0, Warnings: 0, Errors: 0, Failures: 0
```

```
→ php74 vendor/bin/phpbench  run benchmarks/HasNewServicesBench.php 
PHPBench @git_tag@ running benchmarks...
with configuration file: /Users/max/git/laminas/laminas-servicemanager/phpbench.json
with PHP version 7.4.21, xdebug ✔, opcache ❌

\LaminasBench\ServiceManager\HasNewServicesBench

    benchHasFactory1........................R2 I8 [μ Mo]/r: 0.621 0.619 (μs) [μSD μRSD]/r: 0.011μs 1.77%
    benchHasInvokable1......................R1 I9 [μ Mo]/r: 0.954 0.934 (μs) [μSD μRSD]/r: 0.024μs 2.52%
    benchHasService1........................R1 I0 [μ Mo]/r: 0.600 0.592 (μs) [μSD μRSD]/r: 0.013μs 2.23%
    benchFetchFactoryAlias1.................R5 I9 [μ Mo]/r: 0.950 0.981 (μs) [μSD μRSD]/r: 0.033μs 3.45%
    benchHasRecursiveFactoryAlias1..........R2 I8 [μ Mo]/r: 0.942 0.924 (μs) [μSD μRSD]/r: 0.026μs 2.80%
    benchFetchRecursiveFactoryAlias2........R1 I3 [μ Mo]/r: 0.995 1.013 (μs) [μSD μRSD]/r: 0.029μs 2.94%
    benchFetchAbstractFactoryFoo............R2 I6 [μ Mo]/r: 1.107 1.114 (μs) [μSD μRSD]/r: 0.020μs 1.83%

(best [mean mode] worst) = 0.585 [0.881 0.882] 0.628 (μs)
⅀T: 61.683μs μSD/r 0.022μs μRSD/r: 2.506%
Subjects: 7, Assertions: 0, Warnings: 0, Errors: 0, Failures: 0
```

2021-07-24 12:59 UTC, boesing commented
@koenkivits This is awesome. I've double checked your implementation locally and also tried avoiding recursive method calls with using `do-while`.
When using `do-while`, I get some better results while losing readability.

```php
/**
     * Check if a static service or factory exists for the given name.
     */
    private function staticServiceOrFactoryCanCreate(string $name): bool
    {
        $resolvedName = $name;
        do {
            if (isset($this->services[$resolvedName]) || isset($this->factories[$resolvedName])) {
                return true;
            }

            $previousName = $resolvedName;
        } while (($resolvedName = $this->aliases[$resolvedName] ?? $resolvedName) !== $previousName);

        return false;
    }

    /**
     * Check if an abstract factory exists that can create a service for the given name.
     */
    private function abstractFactoryCanCreate(string $name): bool
    {
        $resolvedName = $name;

        do {
            foreach ($this->abstractFactories as $abstractFactory) {
                if ($abstractFactory->canCreate($this->creationContext, $resolvedName)) {
                    return true;
                }
            }

            $previousName = $resolvedName;
        } while (($resolvedName = $this->aliases[$resolvedName] ?? $resolvedName) !== $previousName);

        return false;
    }
```
----

**\LaminasBench\ServiceManager\HasCachedServicesBench**

(best [mean mode] worst) = 0.552 [0.683 0.684] 0.581 (μs)
----
**\LaminasBench\ServiceManager\HasNewServicesBench**

(best [mean mode] worst) = 0.566 [0.747 0.746] 0.615 (μs)

----

Thoughts?

2021-07-24 16:14 UTC, internalsystemerror commented
Oh wow! Nice work. @boesing did you happen to see how many/if any opacaching made a difference during benchmarking?

2021-07-24 16:38 UTC, boesing commented
> Oh wow! Nice work. @boesing did you happen to see how many/if any opacaching made a difference during benchmarking?
Sadly no, I am not that familiar with all that opcache stuff yet as I mainly work with PHP 7.3 in my daily work.

2021-07-24 16:51 UTC, Ocramius commented
I'll do a local run with:
 * PHP 8
 * OpCache 
 * disabled CPU turbo boosting (it breaks benchmark results massively otherwise 😬)

Then I'll most likely merge+release, and add the results as merge commit messages 👍

Fantastic work, @koenkivits and @boesing!

2021-07-24 18:07 UTC, koenkivits commented
I wasn't able to comment since I posted this, but awesome to see this being followed up on so quickly. Thanks @boesing and @Ocramius!

@boesing thanks for checking and adding the benchmark! Regarding the `do-while`: I'm not against sacrificing a little bit of readability for better performance in cases like this, although I'm not sure if the difference in performance is enough in that case. It's hard for me to make that call as an outsider, though. :)

2021-07-24 18:22 UTC, Ocramius commented
> I'm not sure if the difference in performance is enough in that case

`laminas/laminas-servicemanager` being at the very core of most of `laminas/*` kinda makes it worth it.

2021-07-24 19:22 UTC, Ocramius commented
Here's a report of what I've run, after enabling `OpCache`, disabling `Xdebug`, and disabling turbo-boost on my system (`Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz`):


Before:

```
❯ ./vendor/bin/phpbench run --tag=before_93
PHPBench (1.0.4) running benchmarks...
with configuration file: /home/ocramius/Documents/laminas/laminas-servicemanager/phpbench.json
with PHP version 8.0.8, xdebug ❌, opcache ✔

\LaminasBench\ServiceManager\HasNewServicesBench

    benchHasFactory1........................R2 I7 - Mo0.925μs (±0.58%)
    benchHasInvokable1......................R1 I0 - Mo1.068μs (±2.06%)
    benchHasService1........................R1 I0 - Mo0.894μs (±2.24%)
    benchFetchFactoryAlias1.................R1 I9 - Mo1.062μs (±1.98%)
    benchHasRecursiveFactoryAlias1..........R1 I9 - Mo1.067μs (±1.90%)
    benchFetchRecursiveFactoryAlias2........R1 I4 - Mo1.061μs (±0.69%)
    benchFetchAbstractFactoryFoo............R1 I9 - Mo1.212μs (±1.03%)
    benchNonExistingService.................R1 I2 - Mo1.278μs (±0.74%)

\LaminasBench\ServiceManager\FetchNewServiceViaConfigAbstractFactoryBench

    benchFetchServiceWithNoDependencies.....R1 I4 - Mo2.801μs (±1.79%)
    benchBuildServiceWithNoDependencies.....R1 I5 - Mo2.692μs (±2.00%)
    benchFetchServiceDependingOnConfig......R1 I1 - Mo3.213μs (±2.89%)
    benchBuildServiceDependingOnConfig......R1 I1 - Mo3.036μs (±1.87%)
    benchFetchServiceWithDependency.........R1 I7 - Mo3.113μs (±1.78%)
    benchBuildServiceWithDependency.........R1 I7 - Mo2.968μs (±2.05%)

\LaminasBench\ServiceManager\FetchNewServicesBench

    benchFetchFactory1......................R1 I4 - Mo0.879μs (±2.23%)
    benchBuildFactory1......................R2 I8 - Mo0.736μs (±2.14%)
    benchFetchInvokable1....................R1 I9 - Mo0.997μs (±2.31%)
    benchBuildInvokable1....................R1 I7 - Mo0.795μs (±1.61%)
    benchFetchService1......................R1 I9 - Mo0.180μs (±1.83%)
    benchFetchFactoryAlias1.................R1 I7 - Mo0.709μs (±1.49%)
    benchBuildFactoryAlias1.................R1 I8 - Mo0.766μs (±2.84%)
    benchFetchRecursiveFactoryAlias1........R8 I9 - Mo0.714μs (±2.10%)
    benchBuildRecursiveFactoryAlias1........R2 I7 - Mo0.742μs (±2.71%)
    benchFetchRecursiveFactoryAlias2........R1 I4 - Mo0.781μs (±2.64%)
    benchBuildRecursiveFactoryAlias2........R6 I9 - Mo0.771μs (±2.97%)
    benchFetchAbstractFactoryFoo............R10 I9 - Mo0.683μs (±2.01%)
    benchBuildAbstractFactoryFoo............R1 I9 - Mo0.527μs (±1.57%)

\LaminasBench\ServiceManager\FetchNewServiceUsingReflectionAbstractFactoryAsFactoryBench

    benchFetchServiceWithNoDependencies.....R1 I9 - Mo1.072μs (±1.42%)
    benchBuildServiceWithNoDependencies.....R1 I9 - Mo0.971μs (±1.10%)
    benchFetchServiceDependingOnConfig......R2 I1 - Mo3.003μs (±1.46%)
    benchBuildServiceDependingOnConfig......R2 I5 - Mo3.003μs (±2.81%)
    benchFetchServiceWithDependency.........R1 I3 - Mo4.076μs (±2.67%)
    benchBuildServiceWithDependency.........R1 I9 - Mo4.098μs (±2.34%)

\LaminasBench\ServiceManager\FetchCachedServicesBench

    benchFetchFactory1......................R3 I18 - Mo0.189μs (±1.56%)
    benchFetchInvokable1....................R2 I17 - Mo0.367μs (±1.03%)
    benchFetchService1......................R2 I10 - Mo0.178μs (±2.43%)
    benchFetchAlias1........................R2 I9 - Mo0.189μs (±2.46%)
    benchFetchRecursiveAlias1...............R1 I4 - Mo0.180μs (±1.90%)
    benchFetchRecursiveAlias2...............R2 I17 - Mo0.179μs (±2.25%)
    benchFetchAbstractFactoryService........R4 I17 - Mo0.726μs (±3.13%)

\LaminasBench\ServiceManager\FetchNewServiceViaReflectionAbstractFactoryBench

    benchFetchServiceWithNoDependencies.....R2 I3 - Mo1.100μs (±1.40%)
    benchBuildServiceWithNoDependencies.....R1 I3 - Mo1.012μs (±1.33%)
    benchFetchServiceDependingOnConfig......R1 I4 - Mo3.174μs (±1.78%)
    benchBuildServiceDependingOnConfig......R1 I0 - Mo3.080μs (±0.87%)
    benchFetchServiceWithDependency.........R2 I3 - Mo4.319μs (±2.09%)
    benchBuildServiceWithDependency.........R1 I4 - Mo4.216μs (±2.76%)

\LaminasBench\ServiceManager\SetNewServicesBench

    benchSetService.........................R1 I5 - Mo0.267μs (±2.40%)
    benchSetFactory.........................R1 I6 - Mo0.875μs (±3.09%)
    benchSetAlias...........................R1 I6 - Mo1.361μs (±0.68%)
    benchSetAliasOverrided..................R2 I9 - Mo1.355μs (±1.71%)

\LaminasBench\ServiceManager\HasCachedServicesBench

    benchHasFactory1........................R3 I18 - Mo0.900μs (±2.50%)
    benchHasInvokable1......................R1 I11 - Mo1.045μs (±1.21%)
    benchHasService1........................R2 I16 - Mo0.898μs (±2.48%)
    benchHasAlias1..........................R1 I9 - Mo0.899μs (±1.08%)
    benchHasRecursiveAlias1.................R1 I0 - Mo0.894μs (±2.23%)
    benchHasRecursiveAlias2.................R1 I3 - Mo0.895μs (±1.89%)
    benchHasAbstractFactoryService..........R2 I10 - Mo1.182μs (±2.56%)
    benchNonExistingService.................R3 I17 - Mo1.284μs (±2.27%)

\LaminasBench\ServiceManager\FetchNewServiceUsingConfigAbstractFactoryAsFactoryBench

    benchFetchServiceWithNoDependencies.....R1 I9 - Mo2.135μs (±2.61%)
    benchBuildServiceWithNoDependencies.....R1 I6 - Mo1.953μs (±1.76%)
    benchFetchServiceDependingOnConfig......R1 I7 - Mo2.434μs (±1.94%)
    benchBuildServiceDependingOnConfig......R1 I0 - Mo2.279μs (±2.35%)
    benchFetchServiceWithDependency.........R1 I4 - Mo2.429μs (±1.87%)
    benchBuildServiceWithDependency.........R1 I0 - Mo2.347μs (±2.55%)

\LaminasBench\ServiceManager\FetchNewServiceManagerBench

    benchFetchServiceManagerCreation........R4 I16 - Mo364.622μs (±2.83%)

Subjects: 65, Assertions: 0, Failures: 0, Errors: 0
Storing results ... OK
Run: 1346424b68630a03bfdce5e5890625bb81e681a1
```

After:

```
❯ ./vendor/bin/phpbench run --ref=before_93
PHPBench (1.0.4) running benchmarks...
with configuration file: /home/ocramius/Documents/laminas/laminas-servicemanager/phpbench.json
with PHP version 8.0.8, xdebug ❌, opcache ✔
comparing [actual vs. before_93]

\LaminasBench\ServiceManager\HasNewServicesBench

    benchHasFactory1........................R1 I7 - [Mo0.203μs vs. Mo0.925μs] -78.09% (±2.08%)
    benchHasInvokable1......................R9 I9 - [Mo0.277μs vs. Mo1.068μs] -74.10% (±2.14%)
    benchHasService1........................R1 I6 - [Mo0.184μs vs. Mo0.894μs] -79.37% (±1.18%)
    benchFetchFactoryAlias1.................R1 I9 - [Mo0.274μs vs. Mo1.062μs] -74.18% (±0.57%)
    benchHasRecursiveFactoryAlias1..........R1 I5 - [Mo0.275μs vs. Mo1.067μs] -74.25% (±1.51%)
    benchFetchRecursiveFactoryAlias2........R1 I9 - [Mo0.274μs vs. Mo1.061μs] -74.22% (±1.51%)
    benchFetchAbstractFactoryFoo............R1 I9 - [Mo0.315μs vs. Mo1.212μs] -74.01% (±1.71%)
    benchNonExistingService.................R1 I5 - [Mo0.346μs vs. Mo1.278μs] -72.90% (±1.72%)

\LaminasBench\ServiceManager\FetchNewServiceViaConfigAbstractFactoryBench

    benchFetchServiceWithNoDependencies.....R7 I9 - [Mo1.189μs vs. Mo2.801μs] -57.56% (±2.39%)
    benchBuildServiceWithNoDependencies.....R4 I9 - [Mo1.107μs vs. Mo2.692μs] -58.87% (±1.89%)
    benchFetchServiceDependingOnConfig......R1 I4 - [Mo1.466μs vs. Mo3.213μs] -54.37% (±2.68%)
    benchBuildServiceDependingOnConfig......R4 I6 - [Mo1.360μs vs. Mo3.036μs] -55.19% (±2.23%)
    benchFetchServiceWithDependency.........R1 I0 - [Mo1.452μs vs. Mo3.113μs] -53.34% (±1.57%)
    benchBuildServiceWithDependency.........R1 I8 - [Mo1.346μs vs. Mo2.968μs] -54.66% (±1.80%)

\LaminasBench\ServiceManager\FetchNewServicesBench

    benchFetchFactory1......................R1 I3 - [Mo0.863μs vs. Mo0.879μs] -1.85% (±1.73%)
    benchBuildFactory1......................R1 I6 - [Mo0.712μs vs. Mo0.736μs] -3.23% (±1.90%)
    benchFetchInvokable1....................R1 I9 - [Mo0.978μs vs. Mo0.997μs] -1.93% (±2.49%)
    benchBuildInvokable1....................R4 I7 - [Mo0.795μs vs. Mo0.795μs] -0.06% (±2.05%)
    benchFetchService1........ [...]

2021-07-24 19:23 UTC, Ocramius approved these changes

2021-07-24 19:23 UTC, merged

2021-07-24 19:24 UTC, Ocramius commented
Thanks  @koenkivits, @boesing!